export const mapQuyTrinhRoute = {
        GIAOKEHOACHSANXUAT: '/quantri/kehoachsanxuat/giaokehoachsanxuat/',
        TRIENKHAIKEHOACHSANXUAT: '/quantri/kehoachsanxuat/trienkhaikehoachsanxuat/',
        PHIEUNHAPLOBONG:'/quantri/quanlykhosanxuat/khobong/nhapkho/',
        PHIEUNHAPLOBONG_CHATLUONG:'/quantri/quanlykhosanxuat/khobong/thongsochatluong/',
        KEHOACHNHAPNGUYENLIEU:'/quantri/quanlykhosanxuat/khobong/kehoachnhapnguyenlieu/',
        KEHOACHXUATHANG:'/quantri/quanlysanxuatkhothanhpham/khothanhpham/kehoachxuathang/',
        KIEMTRACHATLUONGSOI:'/quantri/quanlysanxuatkhohoiam/khohoiam/chatluongsoi/',
        PHIEUHACAP:'/quantri/quanlysanxuatkhohoiam/khohoiam/hacap/',
        NHAPHOIAM:'/quantri/quanlysanxuatkhohoiam/khohoiam/nhapkho/',
        THONGKESANLUONG:'/quantri/theodoithongkebaocaosanxuat/thongkesanluong/',
        PHUONGANPHABONG:'/quantri/trienkhaisanxuat/phabong/',
        PHUONGANTIMBONG:'/quantri/trienkhaisanxuat/timbong/',
        PHUONGANXEPBANBONG:'/quantri/trienkhaisanxuat/xepbanbong/',
        PHUONGANSANXUAT: '/quantri/kehoachsanxuat/sanxuat/',
        DIEUCHINHDOIKIENBONG:'',
        PHIEUXUATBONG:'/quantri/quanlykhosanxuat/khobong/xuatkho/',
        PHIEUXUATBONGPHE:'/quantri/quanlykhosanxuatbongkhac/khobongphe/xuatkho/',
        PHIEUXUATXO:'/quantri/quanlykhosanxuat/khoxo/xuatkho/',
        XUATTHANHPHAM:'/quantri/quanlysanxuatkhothanhpham/khothanhpham/xuatkhothanhpham/',
        NHAPTHANHPHAM:'/quantri/quanlysanxuatkhothanhpham/khothanhpham/nhapkho/',
        KIEMKEBANCHEPHAM:'',
        CANDOICHUYEN: '',
        DIEUCHUYENKHO:'',
        KIEMKEKHOHANGNGAY:'',

}